FROM archlinux/base

RUN pacman -Sy --noconfirm shards crystal imagemagick librsvg \
    which pkgconf gcc ttf-liberation && \
    git clone https://github.com/flourgaz/invidious

WORKDIR /invidious

RUN sed -i 's/host: localhost/host: postgres/' config/config.yml && \
    shards && \
    crystal build src/invidious.cr

EXPOSE 3000

CMD [ "/invidious/invidious" ]
